backend:
  name: git-gateway
  branch: main # or 'master' depending on your repo's default branch

media_folder: "assets/uploads" # Folder for uploaded files
public_folder: "/assets/uploads"

collections:
  - name: "projects" # Folder for your portfolio projects
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
